- name: Create JDK symbolic links in /usr/lib and /usr/share
  file:
    src={{ item.target }}
    dest={{ item.symlink }}
    state=link
  with_items:
    - { target: '/usr/lib/jvm-exports/java-1.6.0-openjdk.x86_64',           symlink: '/etc/alternatives/java_sdk_1.6.0_exports' }
    - { target: '/usr/lib/jvm-exports/java-1.6.0-openjdk.x86_64',           symlink: '/etc/alternatives/java_sdk_exports' }
    - { target: '/usr/lib/jvm-exports/java-1.6.0-openjdk.x86_64',           symlink: '/etc/alternatives/java_sdk_openjdk_exports' }
    - { target: '/usr/lib/jvm-exports/jre-1.6.0-openjdk.x86_64',            symlink: '/etc/alternatives/jre_1.6.0_exports' }
    - { target: '/usr/lib/jvm-exports/jre-1.6.0-openjdk.x86_64',            symlink: '/etc/alternatives/jre_exports' }
    - { target: '/usr/lib/jvm-exports/jre-1.6.0-openjdk.x86_64',            symlink: '/etc/alternatives/jre_openjdk_exports' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/appletviewer',  symlink: '/etc/alternatives/appletviewer' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/apt',           symlink: '/etc/alternatives/apt' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/extcheck',      symlink: '/etc/alternatives/extcheck' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jarsigner',     symlink: '/etc/alternatives/jarsigner' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jar',           symlink: '/etc/alternatives/jar' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/javac',         symlink: '/etc/alternatives/javac' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/javadoc',       symlink: '/etc/alternatives/javadoc' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/javah',         symlink: '/etc/alternatives/javah' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/javap',         symlink: '/etc/alternatives/javap' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jconsole',      symlink: '/etc/alternatives/jconsole' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jdb',           symlink: '/etc/alternatives/jdb' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jhat',          symlink: '/etc/alternatives/jhat' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jinfo',         symlink: '/etc/alternatives/jinfo' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jmap',          symlink: '/etc/alternatives/jmap' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jps',           symlink: '/etc/alternatives/jps' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jrunscript',    symlink: '/etc/alternatives/jrunscript' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jsadebugd',     symlink: '/etc/alternatives/jsadebugd' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jstack',        symlink: '/etc/alternatives/jstack' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jstatd',        symlink: '/etc/alternatives/jstatd' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/jstat',         symlink: '/etc/alternatives/jstat' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/native2ascii',  symlink: '/etc/alternatives/native2ascii' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/policytool',    symlink: '/etc/alternatives/policytool' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/rmic',          symlink: '/etc/alternatives/rmic' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/schemagen',     symlink: '/etc/alternatives/schemagen' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/serialver',     symlink: '/etc/alternatives/serialver' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/wsgen',         symlink: '/etc/alternatives/wsgen' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/wsimport',      symlink: '/etc/alternatives/wsimport' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64/bin/xjc',           symlink: '/etc/alternatives/xjc' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64',                   symlink: '/etc/alternatives/java_sdk' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64',                   symlink: '/etc/alternatives/java_sdk_1.6.0' }
    - { target: '/usr/lib/jvm/java-1.6.0-openjdk.x86_64',                   symlink: '/etc/alternatives/java_sdk_openjdk' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java',           symlink: '/etc/alternatives/java' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/keytool',        symlink: '/etc/alternatives/keytool' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/orbd',           symlink: '/etc/alternatives/orbd' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/pack200',        symlink: '/etc/alternatives/pack200' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/rmid',           symlink: '/etc/alternatives/rmid' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/rmiregistry',    symlink: '/etc/alternatives/rmiregistry' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/servertool',     symlink: '/etc/alternatives/servertool' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/tnameserv',      symlink: '/etc/alternatives/tnameserv' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/unpack200',      symlink: '/etc/alternatives/unpack200' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64',                    symlink: '/etc/alternatives/jre' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64',                    symlink: '/etc/alternatives/jre_1.6.0' }
    - { target: '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64',                    symlink: '/etc/alternatives/jre_openjdk' }
    - { target: '/usr/share/man/man1/appletviewer-java-1.6.0-openjdk.1.gz', symlink: '/etc/alternatives/appletviewer.1.gz' }
    - { target: '/usr/share/man/man1/apt-java-1.6.0-openjdk.1.gz',          symlink: '/etc/alternatives/apt.1.gz' }
    - { target: '/usr/share/man/man1/extcheck-java-1.6.0-openjdk.1.gz',     symlink: '/etc/alternatives/extcheck.1.gz' }
    - { target: '/usr/share/man/man1/jar-java-1.6.0-openjdk.1.gz',          symlink: '/etc/alternatives/jar.1.gz' }
    - { target: '/usr/share/man/man1/jarsigner-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/jarsigner.1.gz' }
    - { target: '/usr/share/man/man1/javac-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/javac.1.gz' }
    - { target: '/usr/share/man/man1/javadoc-java-1.6.0-openjdk.1.gz',      symlink: '/etc/alternatives/javadoc.1.gz' }
    - { target: '/usr/share/man/man1/javah-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/javah.1.gz' }
    - { target: '/usr/share/man/man1/java-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/java.1.gz' }
    - { target: '/usr/share/man/man1/javap-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/javap.1.gz' }
    - { target: '/usr/share/man/man1/jconsole-java-1.6.0-openjdk.1.gz',     symlink: '/etc/alternatives/jconsole.1.gz' }
    - { target: '/usr/share/man/man1/jdb-java-1.6.0-openjdk.1.gz',          symlink: '/etc/alternatives/jdb.1.gz' }
    - { target: '/usr/share/man/man1/jhat-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/jhat.1.gz' }
    - { target: '/usr/share/man/man1/jinfo-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/jinfo.1.gz' }
    - { target: '/usr/share/man/man1/jmap-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/jmap.1.gz' }
    - { target: '/usr/share/man/man1/jps-java-1.6.0-openjdk.1.gz',          symlink: '/etc/alternatives/jps.1.gz' }
    - { target: '/usr/share/man/man1/jrunscript-java-1.6.0-openjdk.1.gz',   symlink: '/etc/alternatives/jrunscript.1.gz' }
    - { target: '/usr/share/man/man1/jsadebugd-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/jsadebugd.1.gz' }
    - { target: '/usr/share/man/man1/jstack-java-1.6.0-openjdk.1.gz',       symlink: '/etc/alternatives/jstack.1.gz' }
    - { target: '/usr/share/man/man1/jstatd-java-1.6.0-openjdk.1.gz',       symlink: '/etc/alternatives/jstatd.1.gz' }
    - { target: '/usr/share/man/man1/jstat-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/jstat.1.gz' }
    - { target: '/usr/share/man/man1/keytool-java-1.6.0-openjdk.1.gz',      symlink: '/etc/alternatives/keytool.1.gz' }
    - { target: '/usr/share/man/man1/native2ascii-java-1.6.0-openjdk.1.gz', symlink: '/etc/alternatives/native2ascii.1.gz' }
    - { target: '/usr/share/man/man1/orbd-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/orbd.1.gz' }
    - { target: '/usr/share/man/man1/pack200-java-1.6.0-openjdk.1.gz',      symlink: '/etc/alternatives/pack200.1.gz' }
    - { target: '/usr/share/man/man1/policytool-java-1.6.0-openjdk.1.gz',   symlink: '/etc/alternatives/policytool.1.gz' }
    - { target: '/usr/share/man/man1/rmic-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/rmic.1.gz' }
    - { target: '/usr/share/man/man1/rmid-java-1.6.0-openjdk.1.gz',         symlink: '/etc/alternatives/rmid.1.gz' }
    - { target: '/usr/share/man/man1/rmiregistry-java-1.6.0-openjdk.1.gz',  symlink: '/etc/alternatives/rmiregistry.1.gz' }
    - { target: '/usr/share/man/man1/schemagen-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/schemagen.1.gz' }
    - { target: '/usr/share/man/man1/serialver-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/serialver.1.gz' }
    - { target: '/usr/share/man/man1/servertool-java-1.6.0-openjdk.1.gz',   symlink: '/etc/alternatives/servertool.1.gz' }
    - { target: '/usr/share/man/man1/tnameserv-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/tnameserv.1.gz' }
    - { target: '/usr/share/man/man1/unpack200-java-1.6.0-openjdk.1.gz',    symlink: '/etc/alternatives/unpack200.1.gz' }
    - { target: '/usr/share/man/man1/wsgen-java-1.6.0-openjdk.1.gz',        symlink: '/etc/alternatives/wsgen.1.gz' }
    - { target: '/usr/share/man/man1/wsimport-java-1.6.0-openjdk.1.gz',     symlink: '/etc/alternatives/wsimport.1.gz' }
    - { target: '/usr/share/man/man1/xjc-java-1.6.0-openjdk.1.gz',          symlink: '/etc/alternatives/xjc.1.gz' }
  tags:
    - java-alternatives

- name: Create JDK symbolic links in /usr/bin
  file:
    src={{ item.target }}
    dest={{ item.symlink }}
    state=link
  with_items:
    - { symlink: '/usr/bin/appletviewer', target: '/etc/alternatives/appletviewer' }
    - { symlink: '/usr/bin/extcheck',     target: '/etc/alternatives/extcheck'     }
    - { symlink: '/usr/bin/jar',          target: '/etc/alternatives/jar'          }
    - { symlink: '/usr/bin/jarsigner',    target: '/etc/alternatives/jarsigner'    }
    - { symlink: '/usr/bin/java',         target: '/etc/alternatives/java'         }
    - { symlink: '/usr/bin/javac',        target: '/etc/alternatives/javac'        }
    - { symlink: '/usr/bin/javadoc',      target: '/etc/alternatives/javadoc'      }
    - { symlink: '/usr/bin/javah',        target: '/etc/alternatives/javah'        }
    - { symlink: '/usr/bin/javap',        target: '/etc/alternatives/javap'        }
    - { symlink: '/usr/bin/jconsole',     target: '/etc/alternatives/jconsole'     }
    - { symlink: '/usr/bin/jdb',          target: '/etc/alternatives/jdb'          }
    - { symlink: '/usr/bin/jhat',         target: '/etc/alternatives/jhat'         }
    - { symlink: '/usr/bin/jinfo',        target: '/etc/alternatives/jinfo'        }
    - { symlink: '/usr/bin/jmap',         target: '/etc/alternatives/jmap'         }
    - { symlink: '/usr/bin/jps',          target: '/etc/alternatives/jps'          }
    - { symlink: '/usr/bin/jrunscript',   target: '/etc/alternatives/jrunscript'   }
    - { symlink: '/usr/bin/jsadebugd',    target: '/etc/alternatives/jsadebugd'    }
    - { symlink: '/usr/bin/jstack',       target: '/etc/alternatives/jstack'       }
    - { symlink: '/usr/bin/jstat',        target: '/etc/alternatives/jstat'        }
    - { symlink: '/usr/bin/jstatd',       target: '/etc/alternatives/jstatd'       }
    - { symlink: '/usr/bin/keytool',      target: '/etc/alternatives/keytool'      }
    - { symlink: '/usr/bin/native2ascii', target: '/etc/alternatives/native2ascii' }
    - { symlink: '/usr/bin/orbd',         target: '/etc/alternatives/orbd'         }
    - { symlink: '/usr/bin/pack200',      target: '/etc/alternatives/pack200'      }
    - { symlink: '/usr/bin/policytool',   target: '/etc/alternatives/policytool'   }
    - { symlink: '/usr/bin/rmic',         target: '/etc/alternatives/rmic'         }
    - { symlink: '/usr/bin/rmid',         target: '/etc/alternatives/rmid'         }
    - { symlink: '/usr/bin/rmiregistry',  target: '/etc/alternatives/rmiregistry'  }
    - { symlink: '/usr/bin/schemagen',    target: '/etc/alternatives/schemagen'    }
    - { symlink: '/usr/bin/serialver',    target: '/etc/alternatives/serialver'    }
    - { symlink: '/usr/bin/servertool',   target: '/etc/alternatives/servertool'   }
    - { symlink: '/usr/bin/tnameserv',    target: '/etc/alternatives/tnameserv'    }
    - { symlink: '/usr/bin/unpack200',    target: '/etc/alternatives/unpack200'    }
    - { symlink: '/usr/bin/wsgen',        target: '/etc/alternatives/wsgen'        }
    - { symlink: '/usr/bin/wsimport',     target: '/etc/alternatives/wsimport'     }
    - { symlink: '/usr/bin/xjc',          target: '/etc/alternatives/xjc'          }
  tags:
    - java-alternatives

- name: Set priorities for alternatives
  copy:
    src={{ item }}
    dest=/var/lib/alternatives/{{ item }}
  with_items:
    - java
    - javac
    - java_sdk_1.6.0
    - java_sdk_openjdk
    - jre_1.6.0
    - jre_openjdk
  tags:
    - java-alternatives
