- name: Install JDK 1.7.0-71
  yum:
    name=java-1.7.0-openjdk-devel-1.7.0.71-2.5.3.1.el6
    state=present
  tags:
    - java-1.7

- name: Lock JDK version to 1.7.0-71
  lineinfile:
    dest=/etc/yum/pluginconf.d/versionlock.list
    regexp=^1:java-1.7.0-openjdk-devel-
    line=1:java-1.7.0-openjdk-devel-1.7.0.71-2.5.3.1.el6.*
  tags:
    - java-1.7
